repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
-   repo: https://github.com/pycqa/pylint
    rev: pylint-2.5.3
    hooks:
    -   id: pylint
        args:
        - --rcfile=.pylintrc
        - --fail-under=10
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    -   id: mypy
        args:
            - --config-file=
            - --ignore-missing-imports 
            - --disallow-untyped-defs 
            - --disallow-incomplete-defs
            - --warn-unused-ignores 
            - --pretty 
            - --show-error-codes 