version: '3'
services:
  server:
    build: 
      context: .
    ports:
      - "8080:8080"
    user: worker
    volumes:
      - ${HOME}/.aws/credentials:/home/worker/.aws/credentials:ro
  fluentd:
    container_name: fluentd
    build: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
  jaeger:
    container_name: jaeger-sidecar
    image: jaegertracing/all-in-one:1.22
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
