version: '3'
services:
  server:
    build: 
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ${HOME}/.aws/credentials:/home/worker/.aws/credentials:ro
  fluentd:
    container_name: fluentd
    build: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"