version: '3'
services:
  server:
    build: 
      context: .
    ports:
      - "8080:8080"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: host.docker.internal:24224
        tag: python3-backend-worker.logs
    volumes:
      - ${HOME}/.aws/credentials:/root/.aws/credentials:ro
  fluentd:
    container_name: fluentd
    build: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"